name: Build app

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install cmake
      uses: lukka/get-cmake@v3.26.0
    - name: Install dependencies
      run: sudo apt install libsdl2-dev 
    - name: Build
      run: mkdir -p build && cd build && cmake ../ && cmake --build . && cpack
  
  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install cmake
      uses: lukka/get-cmake@v3.26.0
    - name: Install MinGW, MSVC and wget
      run: |
        choco install mingw
        choco install wget
        choco install visualstudio2019buildtools
    - name: Install dependencies`
      run: |
        wget -nv https://github.com/libsdl-org/SDL/releases/download/release-2.26.3/SDL2-devel-2.26.3-mingw.zip
        7z x -bd SDL2-devel-2.26.3-mingw.zip
        wget -nv https://github.com/libsdl-org/SDL/releases/download/release-2.26.3/SDL2-devel-2.26.3-VC.zip
        7z x -bd SDL2-devel-2.26.3-VC.zip
    - name: Build with MSVC
      run: mkdir buildMSVC && cd buildMSVC && cmake -G "Visual Studio 17" -DSDL2_DIR=SDL2-devel-2.26.3-VC\cmake -DSDL2_RUNTIME_DIR=[PATH TO SDL2 RUNTIME DIRECTORY] ..\ && cmake --build . && cpack
    - name: Build with MinGW
      run: mkdir buildMinGW && cd buildMinGW && cmake -G "MinGW Makefiles" -DSDL2_DIR=SDL2-devel-2.26.3-mingw\cmake -DSDL2_RUNTIME_DIR=[PATH TO SDL2 RUNTIME DIRECTORY] -DCMAKE_BUILD_TYPE=Release ..\ && cmake --build . && cpack

  macOS:
    name: Build on MacOS
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install cmake
      uses: lukka/get-cmake@v3.26.0
    - name: Install dependencies`
      run: brew install sdl2
    - name: Build
      run: mkdir build && cd build && cmake ../ && cmake --build . && cpack
